### PR TITLE
Updated herokuish to v0.4.0

### PR DESCRIPTION
**Pull request by d1ceward**
Updated to lastest herokuish version (i'm currently working on updating dokku-arch too)

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I do not maintain this anymore on AUR. Please reach out to @josegonzalez - see https://aur.archlinux.org/packages/herokuish/

Thanks

**Comment by josegonzalez** [comment]
This is still fine to open, though the currently supported release is v0.3.36 - we're waiting till the next full release of Dokku before packaging v0.4.0 as a deb package.

Please open a pull request with that version.

**Comment by ayr-ton** [comment]
I just adopted the package. I also added @D1ceWard as a co-maintainer on AUR. 
I will be happy to accept the same PR here:
https://github.com/ayr-ton/PKGBUILDs

We would need to see how could we merge those changes from AUR later. @MorrisJobke Do you want these changes rebased here on official dokku repositories?

**Comment by ayr-ton** [comment]
@D1ceWard I'm merging your commit on AUR manually

**Comment by josegonzalez** [comment]
I would prefer that the any "official" packages are managed through this organization, not a user's personal repository.

**Comment by ayr-ton** [comment]
@josegonzalez AUR is not an official archlinux repository. It is maintained by users personal repositories. If any package took to long to update it could be taken in an anarchy bases.
If this repo is a "Mirror of AUR git repo" it should consider the same rules. Mine is just a mirror as well to keep track on changes, but the official repo is inside AUR.
You could choose to either rebase the changes from `ssh://aur@aur.archlinux.org/dokku.git` or other mirror.

**Pull request closed without merging**
